TOP ?= top

VERILOG = ../src/top/${TOP}.v ../src/pio.v ../src/machine.v \
          ../src/pc.v ../src/decoder.v ../src/divider.v \
	  ../src/isr.v ../src/osr.v ../src/scratch.v ../src/fifo.v

PIN_DEF = io.lpf

include icesugar_pro.mk

